CC      := gcc
CFLAGS  := -Wall -Wextra -O2
TARGET  := main

SRCS := \
    src/fileio.c \
    src/matrix.c \
    src/graph.c \
    src/exact_task.c \
    src/approx_task.c \
    src/main.c

all:
	$(CC) $(CFLAGS) $(SRCS) -o $(TARGET)

clean:
	rm -f $(TARGET)
